### ISSUE TITLE
Render in blade

### ISSUE THREAD

**Issue by kamalkech** [creitive/laravel5-breadcrumbs#3]
In documentation i can't found how render breadcrumb in blade template

**Comment by levacic** [comment]
If you're using the facade, and you've configured the service provider which sets up the singleton, you should be able to just do:

```php
{{ Breadcrumbs::render() }}
```

Otherwise, if you're working on an instance, just pass it to the view somehow and do

```php
{{ $breadcrumbs->render() }}
```

or even just

```php
{{ $breadcrumbs }}
```

I'll close this but let me know if you need more help.
